### ISSUE TITLE
Why is the Extended Euclidean algorithm computed every time rng.prev is called?

### ISSUE THREAD

**Issue by billtubbs** [bobbaluba/rlcg#2]
As far as I can tell (I'm not a C++ programmer), it seems that the following line is executed every time the `ReversibleLCG.prev` method is called:

https://github.com/bobbaluba/rlcg/blob/4515afa8c23bb8e8a7c6a2e0ef4edb6810a9eb51/include/rlcg.hpp#L75

Correct me if I'm wrong but aren't `A` and `M` constant, so wouldn't it be possible to compute `ainverse` once (e.g. at the point of constructing each ReversibleLCG instance)?

**Comment by johanhelsing** [comment]
Actually, I think it is computed at compile time. I think `const` variables in c++ are normally precomputed at compile time if they can be.

In this case we're in a template function, but c++ requires all template variations to be known at compile time, so that shouldn't be a problem, and the value of the instruction is the result of a constexpr function, which i think should be enough for the compiler to figure out out.

Of course it would probably read better with a constexpr variable, I think I didn't use it because the original code was written in 2013 and constexpr *variables* were introduced in c++14, so changing it will bump the requirement for c++ version as well, but that's probably no biggie in 2021 ;)

Thanks for pointing it out :)

**Comment by billtubbs** [comment]
Thanks for responding.  It must be something particular about my compiler (C++17 as defined [here](https://code.visualstudio.com/docs/cpp/config-clang-mac)).  When I ran the code it was re-computing it every time the `prev` method is called.  I moved the above line into the main part of the class definition and that seemed to fix it.

**Comment by johanhelsing** [comment]
How did you test this? Did you look at the actual assembly? Maybe you didn't compile in release mode?

In any case, I decided to bump the requirement to C++17 and make it a constexpr instead of a const, which makes it illegal for it to be computed at runtime.
